version: "3"

services:
  nosql-db:
    image: mongo:7.0-rc
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: proxy
    depends_on:
      - users
      - upload
      - posts
    ports:
      - "80:80"

  users:
    build:
      dockerfile: Dockerfile
      context: users
    container_name: users
    ports:
      - "8001:8001"
      - "50051:50051"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - ./users:/app/users
      - ./protos:/app/protos

  upload:
    build:
      dockerfile: Dockerfile
      context: upload
    container_name: upload
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - ./upload:/app/upload

  posts:
    build:
      dockerfile: Dockerfile
      context: posts
    container_name: posts
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - ./posts:/app/posts
      - ./protos:/app/protos

volumes:
  protos:
