version: '3'

services:

  nosql-db:
    image: mongo:7.0-rc
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  users:
    build:
      dockerfile: Dockerfile
      context: users
    container_name: users
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - ./users:/app/users
      - /app/users/node_modules

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: proxy
    depends_on:
      - users
    ports:
      - "80:80"
