version: "3"

x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  nosql-db:
    image: mongo:5.0.23
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  nginx-proxy:
    image: proxy:1.0.0
    build:
      dockerfile: Dockerfile
      context: proxy
    depends_on:
      - users
      - upload
      - community
    ports:
      - "80:80"

  users:
    image: users:1.0.0
    build:
      dockerfile: Dockerfile
      context: users
    container_name: users
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - ./users:/app/users
      - ./protos:/app/protos

  community:
    image: community:1.0.0
    build:
      dockerfile: Dockerfile
      context: community
    container_name: community
    ports:
      - "8100:8100"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - ./community:/app/community

  upload:
    image: upload:1.0.0
    build:
      dockerfile: Dockerfile
      context: upload
    container_name: upload
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - ./upload:/app/upload
