name: Deploy on QA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_on_qa:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        
      - name: Create users env file
        working-directory: ./users
        run: |
          touch .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo PORT=8000 >> .env
          cat .env
          
      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x '*.git'

      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: aws-actions/configure-aws-credentials
          aws-region: us-east-1

      - name: Deploy on Elastic beanstalk QA Env
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: devorum-server
          environment_name: Devorum-env
          version_label: "ver-${{ github.sha }}"
          # version_label: devorum-server-1.0.0
          region: ap-southeast-1
          deployment_package: deploy.zip

